WIP Filter per field
collective/collective.searchandreplace pull request #50
Opened 2021-04-16 10:24 UTC by gotcha

2021-04-20 20:09 UTC, spereverde commented on collective/searchandreplace/browser/searchreplacetable.pt
> +  value="Aperçu" class="button">
default should be english,  i18n:attributes needed

2021-04-20 20:18 UTC, spereverde requested changes
- small i18n fix needed
- general question: when you click the filter, the results list does not auto-update, you have to manually re-submit the form, probably more difficult to make this work, but in our use case the data is pretty big, so redoing a search takes a while for the user
- everything else seems to be working fine :-)

2021-05-08 08:20 UTC, gotcha commented
>     * small i18n fix needed
> 
>     * general question: when you click the filter, the results list does not auto-update, you have to manually re-submit the form, probably more difficult to make this work, but in our use case the data is pretty big, so redoing a search takes a while for the user
> 
>     * everything else seems to be working fine :-)

- i18n fix done.
- the results do not auto-update because filtering is costly as it has to be done server side. UI would not be very responsive if a new search was launched for each click.
- filtering needs to happen server side because of batching, the results tied to the fields that the user selects might not exist in the current batch (hope this makes sense).

2021-05-11 09:18 UTC, mauritsvanrees approved these changes
I tried it out and looks good to me.

2021-05-25 09:59 UTC, spereverde approved these changes
LGTM, i18n requested changes are done

2021-05-25 10:00 UTC, spereverde commented on collective/searchandreplace/browser/searchreplacetable.pt
> +  value="Aperçu" class="button">
i18n changes are done

2021-05-26 11:33 UTC, gotcha commented
Rebased and merged locally

2021-05-26 11:33 UTC, closed without merging